apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: pcs
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: pcs
    spec:
      containers:
      - name: manager
        volumeMounts:
          - mountPath: /app/signer/ca
            name: podcertificate-signer-ca
            readOnly: true
      volumes:
        - name: podcertificate-signer-ca
          secret:
            optional: false
            secretName: podcertificate-signer-ca
