---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "podcertificate-signer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podcertificate-signer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - {{ include "podcertificate-signer.fullname" . | quote }}
  verbs:
  - get
  - update
